### ISSUE TITLE
Cannot get Two-Factor-Authentication working

### ISSUE THREAD

**Issue by jonasc** [nrdcg/goinwx#1]
Originally I wanted to use [containous/traefik](https://github.com/containous/traefik) with Let's Encrypt and the DNS challenge provided by [go-acme/lego](https://github.com/go-acme/lego) which in turn uses this project.

My problem is that [go-acme/lego](https://github.com/go-acme/lego) does not seem to support a shared secret for TFA, so I tried (with my very very rusty go knowledge) to see whether I can get it running in principle.
From the docs and the example (and how a [corresponding python version works](https://github.com/oGGy990/certbot-dns-inwx/blob/master/certbot_dns_inwx/dns_inwx.py#L121-L128)) it should look something like this:

```go
import "github.com/pquerna/otp/totp"

func main() {
    client := goinwx.NewClient("user", "pass", &goinwx.ClientOptions{Sandbox: true})
    client.Account.Login()
    str, _ := totp.GenerateCode("SHARED_SECRET", time.Now())
    client.Account.Unlock(str)
    // ...
}
```

Sadly already the `Account.Login` returns `(2200) Authentication error` and trying to ignore it and running `Account.Unlock` it returns `(2002) Command use error`.

I don't really understand what is the problem and sadly my go knowledge is to old and rusty that I can see through the code.

I'd be super glad if you could provide some help!

**Comment by ldez** [comment]
Hello,

I improved the login method by returning the response data fd6778d0c0b3d5436512d79b5bbe4e31e1f131d9

But the `client.Account.Login()` did not changed, and this method should work even if you are using TFA.

**Comment by ldez** [comment]
@smueller18 could you try the TFA behavior?

Personally I don't have an INWX account so I cannot test.

**Comment by ldez** [comment]
@jonasc to use the sandbox you have to provide real username and password.

**Comment by jonasc** [comment]
Okay, thanks for your input. It does work now indeed, and I guess, after trying around I must have gotten confused and maybe used an old TOTP Secret or password as I did change things while testing. Sorry for the false report and thanks for your quick reply!

**Comment by smueller18** [comment]
@jonasc please can you check if #2 is understandable

**Comment by jonasc** [comment]
Perfect, thanks a lot!
