### ISSUE TITLE
transferLock type problem

### ISSUE THREAD

**Issue by gvangool** [nrdcg/goinwx#7]
I'm using `goinwx` through the dnscontrol INWX, and I've been getting an error when trying to manage my domains

```
'transferLock' expected type 'int', got unconvertible type 'bool', value: 'true'`
```

Based on the (current) documentation, the API data type is actually a boolean.
https://www.inwx.com/en/help/apidoc/f/ch02s09.html#domain.info

**Comment by ldez** [comment]
Hello, thank you.

Fixed by 64a0a5b2159611b5db34a392e0933b04c1585ba1
